In [1]:
pip install -U fortran-magic


In [2]:
%reload_ext fortranmagic

/usr/local/lib/python3.6/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [3]:
import py_compile

In [6]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True
valor_nunca_negativo= True
jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [5]:
assert ran_the_first_cell, "Oh noes!"

In [7]:
assert valor_nunca_negativo

In [8]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [9]:
array=[True, 'Falso', .36, 1855564564, 5, 'seis']
array

[True, 'Falso', 0.36, 1855564564, 5, 'seis']

In [ ]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [10]:
primer= array[0]
tercero= array[3]
print("El primer valor del arreglo es: ", primer)
print("El tercer valor del arreglo es: ", tercero)

El primer valor del arreglo es:  True
El tercer valor del arreglo es:  1855564564


In [ ]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [14]:
ultimo = array[-1]
antepenultimo= array[-3]
print("el último valor del arreglo es: ", ultimo)
print("el antepenúltimo valor del arreglo es: ", antepenultimo)

el último valor del arreglo es:  seis
el antepenúltimo valor del arreglo es:  1855564564


In [ ]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [16]:
subarreglo = array[2:5]
subarreglo

[0.36, 1855564564, 5]

In [ ]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [18]:
uno_tres= array[:3]
uno_tres

[True, 'Falso', 0.36]

In [ ]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [19]:
des_tres = array[3:]
des_tres

[1855564564, 5, 'seis']

In [ ]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [20]:
array[1:6:2]

['Falso', 1855564564, 'seis']

In [ ]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [21]:
array[::-1]

['seis', 5, 1855564564, 0.36, 'Falso', True]

In [ ]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [22]:
print("Arreglo antes: ", array)
array.append(False)
print("Arreglo ahora: ", array)

Arreglo antes:  [True, 'Falso', 0.36, 1855564564, 5, 'seis']
Arreglo ahora:  [True, 'Falso', 0.36, 1855564564, 5, 'seis', False]


In [ ]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [24]:
num = [6,7,8,9,10]
[x%5 for x in num]

[1, 2, 3, 4, 0]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [ ]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [25]:
astronomos = {'Carl':'Sagan', 'Georges': 'Lemaitre', 'Edwin': 'Hubble'}
astronomos

{'Carl': 'Sagan', 'Edwin': 'Hubble', 'Georges': 'Lemaitre'}

In [ ]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [26]:
astronomos['Tycho']= 'Brahe'
astronomos

{'Carl': 'Sagan', 'Edwin': 'Hubble', 'Georges': 'Lemaitre', 'Tycho': 'Brahe'}

In [ ]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [27]:
del astronomos['Edwin']
astronomos

{'Carl': 'Sagan', 'Georges': 'Lemaitre', 'Tycho': 'Brahe'}

In [ ]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: ignored

In [28]:
astronomos['Carl':'Brahe']

TypeError: ignored

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [29]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [52]:
c= [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
d= [[10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]]

In [30]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [31]:
%%time

matmul(a, b)

CPU times: user 28 µs, sys: 4 µs, total: 32 µs
Wall time: 36 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [53]:
%%time
matmul(c,d)

CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 42 µs


[[84, 90, 96], [201, 216, 231], [318, 342, 366]]

In [32]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.8644043718033942, 0.674966763662034, 0.44079453825085213],
 [0.08388119482706669, 0.8423734412665402, 0.4646437498466335]]

In [33]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 5.68 s, sys: 7.93 ms, total: 5.69 s
Wall time: 5.69 s


In [55]:
%%time
randc = random_matrix(100, 800)
randd = random_matrix(800,100)
resul = matmul(randc, randd)

CPU times: user 1.3 s, sys: 4 ms, total: 1.31 s
Wall time: 1.31 s


In [34]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [35]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [36]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [56]:
lista_datos = [float(j) for j in range(300000)]
arreglo_datos = np.array(lista_datos)

In [37]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 5.97 ms, sys: 1.94 ms, total: 7.92 ms
Wall time: 7.98 ms


333328333350000.0

In [57]:
%%time
python_dot_product(lista_datos, lista_datos)

CPU times: user 22.2 ms, sys: 1e+03 ns, total: 22.2 ms
Wall time: 22 ms


8999955000050000.0

In [38]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 178 µs, sys: 0 ns, total: 178 µs
Wall time: 281 µs


333328333350000.0

In [58]:
%%time
fortran_dot_product(arreglo_datos, arreglo_datos)

CPU times: user 533 µs, sys: 0 ns, total: 533 µs
Wall time: 541 µs


8999955000050000.0

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [59]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [60]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [45]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [61]:
datos = np.array([5 ,6, 7, 8, 9])
datos

array([5, 6, 7, 8, 9])

In [46]:
data + data

array([2, 4, 6, 8])

In [62]:
datos+datos

array([10, 12, 14, 16, 18])

In [47]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 425 µs, sys: 969 µs, total: 1.39 ms
Wall time: 2.89 ms


333328333350000.0

In [63]:
%%time
(arreglo_datos * arreglo_datos).sum()

CPU times: user 1.4 ms, sys: 996 µs, total: 2.39 ms
Wall time: 1.77 ms


8999955000050000.0

In [48]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 360 µs, sys: 3.89 ms, total: 4.25 ms
Wall time: 5.6 ms


333328333350000.0

In [64]:
%%time
arreglo_datos.dot(arreglo_datos)

CPU times: user 1.39 ms, sys: 2 ms, total: 3.39 ms
Wall time: 3.06 ms


8999955000050000.0

In [49]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 232 µs, sys: 16 µs, total: 248 µs
Wall time: 198 µs


333328333350000.0

In [65]:
%%time
fortran_dot_product(arreglo_datos, arreglo_datos)

CPU times: user 530 µs, sys: 4 µs, total: 534 µs
Wall time: 547 µs


8999955000050000.0

In [50]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

In [66]:
datos[0]= 'Hola'

ValueError: ignored

In [67]:
# We also can't grow an array once it's created.
data.append(3)

AttributeError: ignored

In [68]:
datos.append(10)

AttributeError: ignored

In [ ]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

In [69]:
tres_por_tres = datos.reshape(3,3)

ValueError: ignored

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [71]:
nparr = np.array([7,8,9,10,11,12], dtype='int16').reshape(2,3)
print("Arreglo: \n", nparr, sep='')
print("==========")
print("Tipo de dato: ", nparr.dtype)
print("Tamaño: ", nparr.shape)
print("Saltos: ", nparr.strides)
print("Datos en memoria: ", nparr.data.tobytes())

Arreglo: 
[[ 7  8  9]
 [10 11 12]]
Tipo de dato:  int16
Tamaño:  (2, 3)
Saltos:  (6, 2)
Datos en memoria:  b'\x07\x00\x08\x00\t\x00\n\x00\x0b\x00\x0c\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [39]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
redim = np.arange(18).reshape(6,3)
redim

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [40]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [77]:
redim * redim

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196],
       [225, 256, 289]])

In [41]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [78]:
np.sqrt(redim)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563]])

In [42]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [79]:
(redim % 7) !=0 

array([[False,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [43]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [81]:
((redim % 7 != 0)) & (redim % 2 ==0)

array([[False, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False]])

In [44]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [82]:
redim @ redim.T

array([[  5,  14,  23,  32,  41,  50],
       [ 14,  50,  86, 122, 158, 194],
       [ 23,  86, 149, 212, 275, 338],
       [ 32, 122, 212, 302, 392, 482],
       [ 41, 158, 275, 392, 509, 626],
       [ 50, 194, 338, 482, 626, 770]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [83]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [103]:
senos = np.sin(np.linspace(1, 3.1415, 45))
cosenos  = np.cos(np.linspace(1, 3.1415, 45))
senos

array([8.41470985e-01, 8.66760916e-01, 8.89998057e-01, 9.11127376e-01,
       9.30098830e-01, 9.46867489e-01, 9.61393638e-01, 9.73642875e-01,
       9.83586189e-01, 9.91200031e-01, 9.96466369e-01, 9.99372730e-01,
       9.99912232e-01, 9.98083595e-01, 9.93891152e-01, 9.87344831e-01,
       9.78460136e-01, 9.67258109e-01, 9.53765281e-01, 9.38013607e-01,
       9.20040393e-01, 8.99888205e-01, 8.77604771e-01, 8.53242866e-01,
       8.26860186e-01, 7.98519216e-01, 7.68287077e-01, 7.36235368e-01,
       7.02439999e-01, 6.66981010e-01, 6.29942379e-01, 5.91411827e-01,
       5.51480608e-01, 5.10243291e-01, 4.67797543e-01, 4.24243888e-01,
       3.79685477e-01, 3.34227839e-01, 2.87978635e-01, 2.41047397e-01,
       1.93545276e-01, 1.45584773e-01, 9.72794748e-02, 4.87437853e-02,
       9.26535897e-05])

In [84]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [105]:
senos[-1]

9.265358966049026e-05

In [85]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [106]:
senos[:5]

array([0.84147098, 0.86676092, 0.88999806, 0.91112738, 0.93009883])

In [86]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [107]:
senos[6:]

array([9.61393638e-01, 9.73642875e-01, 9.83586189e-01, 9.91200031e-01,
       9.96466369e-01, 9.99372730e-01, 9.99912232e-01, 9.98083595e-01,
       9.93891152e-01, 9.87344831e-01, 9.78460136e-01, 9.67258109e-01,
       9.53765281e-01, 9.38013607e-01, 9.20040393e-01, 8.99888205e-01,
       8.77604771e-01, 8.53242866e-01, 8.26860186e-01, 7.98519216e-01,
       7.68287077e-01, 7.36235368e-01, 7.02439999e-01, 6.66981010e-01,
       6.29942379e-01, 5.91411827e-01, 5.51480608e-01, 5.10243291e-01,
       4.67797543e-01, 4.24243888e-01, 3.79685477e-01, 3.34227839e-01,
       2.87978635e-01, 2.41047397e-01, 1.93545276e-01, 1.45584773e-01,
       9.72794748e-02, 4.87437853e-02, 9.26535897e-05])

In [87]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [108]:
senos[::4]

array([8.41470985e-01, 9.30098830e-01, 9.83586189e-01, 9.99912232e-01,
       9.78460136e-01, 9.20040393e-01, 8.26860186e-01, 7.02439999e-01,
       5.51480608e-01, 3.79685477e-01, 1.93545276e-01, 9.26535897e-05])

In [88]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [109]:
print("Seno: \n", senos)
print("Valores de seno menores a 0.5", senos < 0.5)
print("Valores de seno mayores a 0.5", senos > 0.5)

Seno: 
 [8.41470985e-01 8.66760916e-01 8.89998057e-01 9.11127376e-01
 9.30098830e-01 9.46867489e-01 9.61393638e-01 9.73642875e-01
 9.83586189e-01 9.91200031e-01 9.96466369e-01 9.99372730e-01
 9.99912232e-01 9.98083595e-01 9.93891152e-01 9.87344831e-01
 9.78460136e-01 9.67258109e-01 9.53765281e-01 9.38013607e-01
 9.20040393e-01 8.99888205e-01 8.77604771e-01 8.53242866e-01
 8.26860186e-01 7.98519216e-01 7.68287077e-01 7.36235368e-01
 7.02439999e-01 6.66981010e-01 6.29942379e-01 5.91411827e-01
 5.51480608e-01 5.10243291e-01 4.67797543e-01 4.24243888e-01
 3.79685477e-01 3.34227839e-01 2.87978635e-01 2.41047397e-01
 1.93545276e-01 1.45584773e-01 9.72794748e-02 4.87437853e-02
 9.26535897e-05]
Valores de seno menores a 0.5 [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True  True]

In [89]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [110]:
print(senos)
senos[[0, 4, 7]]

[8.41470985e-01 8.66760916e-01 8.89998057e-01 9.11127376e-01
 9.30098830e-01 9.46867489e-01 9.61393638e-01 9.73642875e-01
 9.83586189e-01 9.91200031e-01 9.96466369e-01 9.99372730e-01
 9.99912232e-01 9.98083595e-01 9.93891152e-01 9.87344831e-01
 9.78460136e-01 9.67258109e-01 9.53765281e-01 9.38013607e-01
 9.20040393e-01 8.99888205e-01 8.77604771e-01 8.53242866e-01
 8.26860186e-01 7.98519216e-01 7.68287077e-01 7.36235368e-01
 7.02439999e-01 6.66981010e-01 6.29942379e-01 5.91411827e-01
 5.51480608e-01 5.10243291e-01 4.67797543e-01 4.24243888e-01
 3.79685477e-01 3.34227839e-01 2.87978635e-01 2.41047397e-01
 1.93545276e-01 1.45584773e-01 9.72794748e-02 4.87437853e-02
 9.26535897e-05]


array([0.84147098, 0.93009883, 0.97364288])

In [90]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [111]:
ddesorden = np. array([0, 99, 1, 50 , -35, -55, 25])

In [91]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [112]:
indices_ordenados = np.argsort(ddesorden)
ddesorden

array([  0,  99,   1,  50, -35, -55,  25])

In [92]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [113]:
ddesorden[indices_ordenados]

array([-55, -35,   0,   1,  25,  50,  99])

In [93]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [114]:
cap_mer = np.array([30, 12, 1 , 69, 4])
bienes = np.array(['A', 'B', 'C', 'D', 'E'])

In [94]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [115]:
cm_ordenado = np.argsort(cap_mer)
bienes[cm_ordenado]

array(['C', 'E', 'B', 'A', 'D'], dtype='<U1')

In [95]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [96]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [97]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [116]:
datos = np.arange(30).reshape(6,5)
datos

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [98]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [117]:
datos[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [99]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [119]:
datos[:2, [0, -2]]

array([[0, 3],
       [5, 8]])

In [100]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [120]:
datos[((datos[:, 0])%3) == 0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [128]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [129]:
variance(np.random.standard_normal(1000))

0.9815765255290951

In [136]:
variance(np.random.standard_normal(2000))

1.024147310100378

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [130]:
data = np.arange(30)
data.mean()

14.5

In [137]:
datos = np.arange(50)
datos.mean()

24.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [131]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [138]:
datos = np.arange(60).reshape(4, 15)
datos

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [132]:
data.mean()

14.5

In [139]:
datos.mean()

29.5

In [133]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [140]:
datos.mean(axis=1)

array([ 7., 22., 37., 52.])

In [134]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [142]:
datos.mean(axis=0)

array([22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5,
       33.5, 34.5, 35.5, 36.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [143]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [146]:
fila = np.array([5,6,7,8,9])
columna= np.array([[10],[11],[12]])
print("Filas: \n", fila, sep='')
print("Columnas: \n", columna, sep='')

Filas: 
[5 6 7 8 9]
Columnas: 
[[10]
 [11]
 [12]]


In [144]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [148]:
fila + columna

array([[15, 16, 17, 18, 19],
       [16, 17, 18, 19, 20],
       [17, 18, 19, 20, 21]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [145]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [150]:
print("Datos: \n", datos, sep='')
print("Promedio: \n", datos.mean(axis=0), sep='')
print("Datos - Promedio: \n", datos - datos.mean(axis=0), sep='')

Datos: 
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]]
Promedio: 
[22.5 23.5 24.5 25.5 26.5 27.5 28.5 29.5 30.5 31.5 32.5 33.5 34.5 35.5
 36.5]
Datos - Promedio: 
[[-22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5 -22.5
  -22.5 -22.5 -22.5]
 [ -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5  -7.5
   -7.5  -7.5  -7.5]
 [  7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5   7.5
    7.5   7.5   7.5]
 [ 22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5  22.5
   22.5  22.5  22.5]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [151]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [165]:
r = pd.Series(index=['a', 'e', 'i', 'o', 'u'], data=[6,7,8,9,10])
r

a     6
e     7
i     8
o     9
u    10
dtype: int64

In [152]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [166]:
print("El índice es: ", r.index)
print("Los valores son: ", r.values)

El índice es:  Index(['a', 'e', 'i', 'o', 'u'], dtype='object')
Los valores son:  [ 6  7  8  9 10]


In [153]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [167]:
r.iloc[0]

6

In [154]:
# ... or by label.
s.loc['a']

1

In [168]:
r.loc['a']

6

In [155]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [169]:
r.iloc[:3]

a    6
e    7
i    8
dtype: int64

In [156]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [171]:
r.loc[:'e']

a    6
e    7
dtype: int64

In [157]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [172]:
r.iloc[[0, -1]]

a     6
u    10
dtype: int64

In [158]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [173]:
r.loc[ r >7]

i     8
o     9
u    10
dtype: int64

In [159]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [174]:
otro_r = pd.Series({'a': 100, 'e':200, 'i':300, 'o':400, 'u':500})
otro_r

a    100
e    200
i    300
o    400
u    500
dtype: int64

In [160]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [175]:
r + otro_r

a    106
e    207
i    308
o    409
u    510
dtype: int64

In [161]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [162]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [176]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [177]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [178]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

In [179]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

NameError: ignored

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [180]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

ModuleNotFoundError: ignored

In [181]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

NameError: ignored

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!